### ISSUE TITLE
Issues loading /etc/pmcf/pmcf.conf

### ISSUE THREAD

**Issue by ktechmidas** [pikselpalette/pmcf#1]
Hi,

Running the standard Amazon Linux EC2 AMI - build went fine. I believe I have set up everything correctly (I built the docs and took a good look) however I'm having some issues when trying to build the test.yaml

[root@ip-172-31-31-185 yaml]# pmcf -p default -a create test.yaml
Traceback (most recent call last):
  File "/usr/local/bin/pmcf", line 9, in <module>
    load_entry_point('pmcf==2014.1', 'console_scripts', 'pmcf')()
  File "/usr/local/lib/python2.7/site-packages/pmcf-2014.1-py2.7.egg/pmcf/cli/cli.py", line 111, in main
    cli = PMCFCLI(options)
  File "/usr/local/lib/python2.7/site-packages/pmcf-2014.1-py2.7.egg/pmcf/cli/cmd.py", line 39, in __init__
    self.parser = import_from_string('pmcf.parsers', args['parser'])()
TypeError: Can't instantiate abstract class BaseParser with abstract methods parse

**Comment by ktechmidas** [comment]
Apologies - /etc/pmcf/pmcf.conf wasn't readable :)
